//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_img_generator.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localHost/WebService", ConfigurationName="ServiceReference1.GetStockArtWSSoap")]
    public interface GetStockArtWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localHost/WebService/GetDetialByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDetialByID(int id, string serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localHost/WebService/GetDetialByID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDetialByIDAsync(int id, string serie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetStockArtWSSoapChannel : api_img_generator.ServiceReference1.GetStockArtWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStockArtWSSoapClient : System.ServiceModel.ClientBase<api_img_generator.ServiceReference1.GetStockArtWSSoap>, api_img_generator.ServiceReference1.GetStockArtWSSoap {
        
        public GetStockArtWSSoapClient() {
        }
        
        public GetStockArtWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetStockArtWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetStockArtWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetStockArtWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDetialByID(int id, string serie) {
            return base.Channel.GetDetialByID(id, serie);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDetialByIDAsync(int id, string serie) {
            return base.Channel.GetDetialByIDAsync(id, serie);
        }
    }
}
