//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_img_generator.ServiceReference3 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.ServicioFormatoSoap")]
    public interface ServicioFormatoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDetialByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDetialByID(string id, string empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDetialByID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDetialByIDAsync(string id, string empresa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioFormatoSoapChannel : api_img_generator.ServiceReference3.ServicioFormatoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFormatoSoapClient : System.ServiceModel.ClientBase<api_img_generator.ServiceReference3.ServicioFormatoSoap>, api_img_generator.ServiceReference3.ServicioFormatoSoap {
        
        public ServicioFormatoSoapClient() {
        }
        
        public ServicioFormatoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFormatoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFormatoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFormatoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDetialByID(string id, string empresa) {
            return base.Channel.GetDetialByID(id, empresa);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDetialByIDAsync(string id, string empresa) {
            return base.Channel.GetDetialByIDAsync(id, empresa);
        }
    }
}
